version: '3'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node
    restart: always
    tty: true
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_DATABASE: desafio_nginx_node
    ports:
      - '3000:3000'
    volumes:
      - node_modules:/app/node_modules
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    tty: true
    ports:
      - '8080:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
  node_modules:
